spring:
  application:
    name: funds-holding-analyser
  profiles:
    active : dev
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    url : jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:funds-holding-analyser}
    #url: jdbc:postgresql://${MF_HOLDING_HOST:localhost}:5432/${MF_HOLDING_DB:funds-holding-analyser}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    shouldRepair: true
    connect-retries: 10
    schemas: public
    baseline-on-migration: true
    placeholderReplacement: false

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
  file:
    name : logs/myapp.log
    path : logs


data:
  extractor:
    months : 6
    max-retry : 5

internal:
  funds:
    vanguard:
      funds-links : https://investor.vanguard.com/investment-products/list/funddetail


