spring:
  application:
    name: funds-holding-analyser
  profiles:
    active: local
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    shouldRepair: true
    baseline-on-migration: true
    placeholderReplacement: false

    #url: jdbc:postgresql://${MF_HOLDING_HOST:localhost}:5432/${MF_HOLDING_DB:funds-holding-analyser}


logging:
  file:
    name : logs/myapp.log
    path : logs


data:
  extractor:
    months : 6
    max-retry : 5

internal:
  funds:
    vanguard:
      funds-links : https://investor.vanguard.com/investment-products/list/funddetail
