INSERT INTO mutual_fund_config (mutual_fund_id, download_url, is_zipped, sheet_name, content_type, extension, isin_col_mapper, stock_col_mapper, industry_col_mapper, quantity_col_mapper, market_value_col_mapper, net_asset_perc_col_mapper, is_pick_by_system, date_mapper_1, date_mapper_2, date_mapper_3, date_mapper_4, date_mapper_1_config, date_mapper_2_config, date_mapper_3_config, date_mapper_4_config)
VALUES
(
    (SELECT id FROM mutual_fund WHERE name = 'Canara Robeco Blue Chip Equity Fund'),
    'https://www.canararobeco.com/docs/default-source/monthly-portfolio/${DATE_MAPPER_1}/combined-monthly-portfolio/lc.xlsx',
    false,
    '',
    'excel',
    'xlsx',
    2,
    1,
    3,
    4,
    5,
    6,
    false,
    'yyyy/MMMM',
    '',
    '',
    '',
    '',
    '',
    '',
    ''
),
(
    (SELECT id FROM mutual_fund WHERE name = 'Canara Robeco Mid Cap Fund'),
    'https://www.canararobeco.com/docs/default-source/monthly-portfolio/${DATE_MAPPER_1}/combined-monthly-portfolio/md.xlsx', -- Replace with actual URL
    false,
    '',
    'excel',
    'xlsx',
    2,
    1,
    3,
    4,
    5,
    6,
    false,
    'yyyy/MMMM', -- Or correct date mapper
    '',
    '',
    '',
    '',
    '',
    '',
    ''
),
(
    (SELECT id FROM mutual_fund WHERE name = 'Canara Robeco Multi Cap Fund'),
    'https://www.canararobeco.com/docs/default-source/monthly-portfolio/${DATE_MAPPER_1}/combined-monthly-portfolio/mf.xlsx', -- Replace with actual URL
    false,
    '',
    'excel',
    'xlsx',
    2,
    1,
    3,
    4,
    5,
    6,
    false,
    'yyyy/MMMM', -- Or correct date mapper
    '',
    '',
    '',
    '',
    '',
    '',
    ''
),
(
    (SELECT id FROM mutual_fund WHERE name = 'Canara Robeco Flexi Cap Fund'),
    'https://www.canararobeco.com/docs/default-source/monthly-portfolio/${DATE_MAPPER_1}/combined-monthly-portfolio/dv.xlsx', -- Replace with actual URL
    false,
    '',
    'excel',
    'xlsx',
    2,
    1,
    3,
    4,
    5,
    6,
    false,
    'yyyy/MMMM', -- Or correct date mapper
    '',
    '',
    '',
    '',
    '',
    '',
    ''
),
(
    (SELECT id FROM mutual_fund WHERE name = 'Canara Robeco Small Cap Fund'),
    'https://www.canararobeco.com/docs/default-source/monthly-portfolio/${DATE_MAPPER_1}/combined-monthly-portfolio/sc.xlsx', -- Replace with actual URL
    false,
    '',
    'excel',
    'xlsx',
    2,
    1,
    3,
    4,
    5,
    6,
    false,
    'yyyy/MMMM', -- Or correct date mapper
    '',
    '',
    '',
    '',
    '',
    '',
    ''
),
(
    (SELECT id FROM mutual_fund WHERE name = 'Canara Robeco Emerging Equities'),
    'https://www.canararobeco.com/docs/default-source/monthly-portfolio/${DATE_MAPPER_1}/combined-monthly-portfolio/eq.xlsx', -- Replace with actual URL
    false,
    '',
    'excel',
    'xlsx',
    2,
    1,
    3,
    4,
    5,
    6,
    false,
    'yyyy/MMMM', -- Or correct date mapper
    '',
    '',
    '',
    '',
    '',
    '',
    ''
),
(
    (SELECT id FROM mutual_fund WHERE name = 'Canara Robeco ELSS Tax Saver'),
    'https://www.canararobeco.com/docs/default-source/monthly-portfolio/${DATE_MAPPER_1}/combined-monthly-portfolio/et.xlsx', -- Replace with actual URL
    false,
    '',
    'excel',
    'xlsx',
    2,
    1,
    3,
    4,
    5,
    6,
    false,
    'yyyy/MMMM', -- Or correct date mapper
    '',
    '',
    '',
    '',
    '',
    '',
    ''
),
(
    (SELECT id FROM mutual_fund WHERE name = 'Canara Robeco Consumer Trends Fund'),
    'https://www.canararobeco.com/docs/default-source/monthly-portfolio/${DATE_MAPPER_1}/combined-monthly-portfolio/cf.xlsx', -- Replace with actual URL
    false,
    '',
    'excel',
    'xlsx',
    2,
    1,
    3,
    4,
    5,
    6,
    false,
    'yyyy/MMMM', -- Or correct date mapper
    '',
    '',
    '',
    '',
    '',
    '',
    ''
),
(
    (SELECT id FROM mutual_fund WHERE name = 'Canara Robeco Infrastructure Fund'),
    'https://www.canararobeco.com/docs/default-source/monthly-portfolio/${DATE_MAPPER_1}/combined-monthly-portfolio/in.xlsx', -- Replace with actual URL
    false,
    '',
    'excel',
    'xlsx',
    2,
    1,
    3,
    4,
    5,
    6,
    false,
    'yyyy/MMMM', -- Or correct date mapper
    '',
    '',
    '',
    '',
    '',
    '',
    ''
),
(
    (SELECT id FROM mutual_fund WHERE name = 'Canara Robeco Focused Equity Fund'),
    'https://www.canararobeco.com/docs/default-source/monthly-portfolio/${DATE_MAPPER_1}/combined-monthly-portfolio/fe.xlsx', -- Replace with actual URL
    false,
    '',
    'excel',
    'xlsx',
    2,
    1,
    3,
    4,
    5,
    6,
    false,
    'yyyy/MMMM', -- Or correct date mapper
    '',
    '',
    '',
    '',
    '',
    '',
    ''
),
(
    (SELECT id FROM mutual_fund WHERE name = 'Canara Robeco Value Fund'),
    'https://www.canararobeco.com/docs/default-source/monthly-portfolio/${DATE_MAPPER_1}/combined-monthly-portfolio/vf.xlsx', -- Replace with actual URL
    false,
    '',
    'excel',
    'xlsx',
    2,
    1,
    3,
    4,
    5,
    6,
    false,
    'yyyy/MMMM', -- Or correct date mapper
    '',
    '',
    '',
    '',
    '',
    '',
    ''
);
