CREATE TABLE IF NOT EXISTS SECTOR (
        ID SERIAL PRIMARY KEY,
        NAME VARCHAR(100),
        DESCRIPTION VARCHAR(500),
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS INDUSTRY (
        ID SERIAL PRIMARY KEY,
        NAME VARCHAR(100),
        DESCRIPTION VARCHAR(500),
        SECTOR_ID INT NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_industry_sector_id FOREIGN KEY(SECTOR_ID) REFERENCES SECTOR(id)
);

CREATE TABLE IF NOT EXISTS STOCK_DETAILS (
    ID SERIAL PRIMARY KEY,
    SYMBOL VARCHAR(50) UNIQUE,
    NAME_OF_COMPANY VARCHAR(100),
    INDUSTRY_ID INT NULL,
    SECTOR_ID INT NULL,
    MKT_CAP INT NULL,
    SERIES VARCHAR(10),
    DATE_OF_LISTING DATE,
    PAID_UP_VALUE INT,
    MARKET_LOT INT,
    ISIN_NUMBER VARCHAR(50),
    FACE_VALUE INT,
    TOTAL_FLOATING_SHARES BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stock_details_sector_id FOREIGN KEY(SECTOR_ID) REFERENCES SECTOR(id),
    CONSTRAINT fk_stock_details_industry_id FOREIGN KEY(INDUSTRY_ID) REFERENCES INDUSTRY(id)
);

CREATE TABLE IF NOT EXISTS MUTUAL_FUND_HOUSE(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) UNIQUE,
    DESCRIPTION  VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FUND_TYPE(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) UNIQUE,
    DESCRIPTION  VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MUTUAL_FUND(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) UNIQUE,
    DESCRIPTION VARCHAR(500),
    MUTUAL_FUND_HOUSE_ID INT,
    FUND_TYPE_ID INT,
    IS_INTERNATION_FUND boolean DEFAULT false,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fund_id FOREIGN KEY(MUTUAL_FUND_HOUSE_ID) REFERENCES MUTUAL_FUND_HOUSE(id),
    CONSTRAINT fk_type_id FOREIGN KEY(FUND_TYPE_ID) REFERENCES FUND_TYPE(id)
);


CREATE TABLE IF NOT EXISTS MUTUAL_FUND_HOLDING(
    ID SERIAL PRIMARY KEY,
    MUTUAL_FUND_ID INT,
    STOCK_ID INT,
    QUANTITY BIGINT,
    MARKET_VALUE DOUBLE PRECISION,
    AVG_PRICE DOUBLE PRECISION,
    NET_ASSET_PCT DOUBLE PRECISION,
    AT_DATE  DATE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mutual_fund_holding_mf_id FOREIGN KEY(MUTUAL_FUND_ID) REFERENCES MUTUAL_FUND(id),
    CONSTRAINT fk_mutual_fund_holding_stock_id FOREIGN KEY(STOCK_ID) REFERENCES STOCK_DETAILS(id)
);


CREATE TABLE IF NOT EXISTS MUTUAL_FUND_CONFIG (
    ID SERIAL PRIMARY KEY,
    MUTUAL_FUND_ID INT NOT NULL,
    DOWNLOAD_URL VARCHAR(200),
    IS_ZIPPED BOOLEAN,
    SHEET_NAME VARCHAR(100),
    CONTENT_TYPE VARCHAR(100),
    EXTENSION VARCHAR(50),
    ISIN_COL_MAPPER INT,
    STOCK_COL_MAPPER INT,
    INDUSTRY_COL_MAPPER INT,
    QUANTITY_COL_MAPPER INT,
    MARKET_VALUE_COL_MAPPER INT,
    NET_ASSET_PERC_COL_MAPPER INT,
    IS_PICK_BY_SYSTEM BOOLEAN,
    DATE_MAPPER_1 VARCHAR(50),
    DATE_MAPPER_2 VARCHAR(50),
    DATE_MAPPER_3 VARCHAR(50),
    DATE_MAPPER_4 VARCHAR(50),
    DATE_MAPPER_1_CONFIG varchar(100),
    DATE_MAPPER_2_CONFIG varchar(100),
    DATE_MAPPER_3_CONFIG varchar(100),
    DATE_MAPPER_4_CONFIG varchar(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mf_config_mutual_fund_id FOREIGN KEY(MUTUAL_FUND_ID) REFERENCES MUTUAL_FUND(id)
);

CREATE TABLE IF NOT EXISTS MF_HOLDING_EXTRACTOR_JOB_HISTORY(
    ID SERIAL PRIMARY KEY,
    MUTUAL_FUND_CONFIG_ID INT NOT NULL,
    URL TEXT,
    AT_DATE  DATE NOT NULL,
    STATUS VARCHAR(50),
    ERROR TEXT,
    RETRY_COUNT INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mf_holding_extractor_mf_id FOREIGN KEY(MUTUAL_FUND_ID) REFERENCES MUTUAL_FUND(id),
    CONSTRAINT fk_mf_holding_extractor_mf_config_id FOREIGN KEY(MUTUAL_FUND_CONFIG_ID) REFERENCES MUTUAL_FUND_CONFIG(id)
);

