CREATE TABLE IF NOT EXISTS MUTUAL_FUND_DOWNLOAD_LINKS(
    ID SERIAL PRIMARY KEY,
    MUTUAL_FUND_ID INT,
    URL TEXT NOT NULL,
    AT_DATE  DATE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mutual_fund_download_link_mf_id FOREIGN KEY(MUTUAL_FUND_ID) REFERENCES MUTUAL_FUND(id)
);