CREATE TABLE IF NOT EXISTS STOCK_PRICE_HISTORY (
    ID BIGSERIAL PRIMARY KEY,
    STOCK_ID INT NOT NULL,
    TRADE_DATE DATE NOT NULL,
    OPEN_PRICE NUMERIC(12,2),
    HIGH_PRICE NUMERIC(12,2),
    LOW_PRICE NUMERIC(12,2),
    CLOSE_PRICE NUMERIC(12,2),
    VOLUME BIGINT,
    NUMBER_OF_TRADES INT,
    TURNOVER NUMERIC(18,2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stock_price_stock_id FOREIGN KEY(STOCK_ID) REFERENCES STOCK_DETAILS(ID),
    UNIQUE(STOCK_ID, TRADE_DATE)
);
