-- Add Bhav Copy columns to stock_price_history table
ALTER TABLE stock_price_history
    ADD COLUMN biz_date DATE,
    ADD COLUMN segment VARCHAR(16),
    ADD COLUMN source VARCHAR(16),
    ADD COLUMN financial_instrument_type VARCHAR(32),
    ADD COLUMN financial_instrument_id VARCHAR(32),
    ADD COLUMN isin VARCHAR(16),
    ADD COLUMN ticker_symbol VARCHAR(16),
    ADD COLUMN security_series VARCHAR(8),
    ADD COLUMN expiry_date DATE,
    ADD COLUMN actual_expiry_date DATE,
    ADD COLUMN strike_price DECIMAL(20,4),
    ADD COLUMN option_type VARCHAR(8),
    ADD COLUMN instrument_name VARCHAR(64),
    ADD COLUMN last_price DECIMAL(20,4),
    ADD COLUMN previous_closing_price DECIMAL(20,4),
    ADD COLUMN underlying_price DECIMAL(20,4),
    ADD COLUMN settlement_price DECIMAL(20,4),
    ADD COLUMN open_interest BIGINT,
    ADD COLUMN change_in_open_interest BIGINT,
    ADD COLUMN total_trading_volume BIGINT,
    ADD COLUMN total_traded_value DECIMAL(20,4),
    ADD COLUMN total_number_of_transactions_executed BIGINT,
    ADD COLUMN session_id VARCHAR(8),
    ADD COLUMN new_board_lot_quantity BIGINT,
    ADD COLUMN remarks VARCHAR(128),
    ADD COLUMN reserved1 VARCHAR(32),
    ADD COLUMN reserved2 VARCHAR(32),
    ADD COLUMN reserved3 VARCHAR(32),
    ADD COLUMN reserved4 VARCHAR(32);

